# Generated by Django 2.0 on 2019-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=300)),
                ('secret', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
    ]
