# Generated by Django 2.0 on 2019-05-31 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190531_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
